### ISSUE TITLE
Participer à un événement

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#11]

**Comment by Kevin-Laipe** [comment]
On pourra utiliser SwiftMailer
https://maurice-chavelli.developpez.com/tutoriels/laravel-5-5/les-bases/?page=envoyer-un-email

**Comment by daviddasilva1** [comment]
L'utilisateur connecté peut maintenant participer à un événement. b66a230faf985013f7d0040bcd17e475dc1e2e98

**Comment by daviddasilva1** [comment]
Il faut que le bouton soit activé seulement si quelqu'un est connecté. Il faut aussi que le texte change de "Je participe" à "Je participe pas" une fois que l'utilisateur a cliqué dessus.

**Comment by daviddasilva1** [comment]
@update : ajout vérification de connexion d'un utilisateur pour activer le bouton 66f1c7c308ec84d811c98b02444895e2b298814a

**Comment by Kevin-Laipe** [comment]
> 
> 
> Il faut aussi que le texte change de "Je participe" à "Je participe pas" une fois que l'utilisateur a cliqué dessus.

On devrait pouvoir vérifier la table 'participates' pour changer le texte et le comportement du bouton (éviter que l'utilisateur x participe plus d'une fois à l'événement y). J'ai essayé un moment, mais sans y arriver (https://laravel.com/docs/5.8/queries#parameter-grouping).

**Comment by daviddasilva1** [comment]
@update : si l'utilisateur clique sur "Je participe" sur un événement auquel il participe déjà, ça supprime son inscription

**Comment by daviddasilva1** [comment]
On utilise maintenant les Eloquent pour pouvoir participer. 7b364a5d5b8b7a39d4bcd0432d4c581cd7dc28ad
f09854f3ed006852234f3bfe8616692bd45dcbe1

**Comment by daviddasilva1** [comment]
On peut maintenant voir le nombre de participants dans chaque événement si on est connecté.
4c7c00336161a867eb3b92c1e4ea2d26aa5d1f18
