### ISSUE TITLE
Création des modèles (DB) avec Eloquent

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#2]

**Comment by daviddasilva1** [comment]
Les tables Events,Participate et Category ont été créées. On utilisera la table users créée par Lavarel pour l'authentification.  ac269c8c0e0f629d3ac4fac606d119de2729d792

**Comment by daviddasilva1** [comment]
Création de différents Seeder pour chaque table. Insertion d'une ligne pour chaque table pour peupler la base de données.

**Comment by daviddasilva1** [comment]
Remplissage de la base de données avec l'utilisation des Seeders
