### ISSUE TITLE
Page de sign in

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#4]

**Comment by ninojeannet** [comment]
8f44ec8d5fe4f18d52ebb12a70178b400fd1701d

Création automatique du login / sign in avec npm en suivant le lien suivant.
https://www.youtube.com/watch?v=hOYW3jqh19I&t=9s

J'ai installé Node.JS ainsi que npm (directement inclut dans Node) puis :
* composer require laravel/ui --dev
* php artisan ui vue --auth
* npm install
* npm run dev

https://laravel.com/docs/6.x/frontend

**Comment by Kevin-Laipe** [comment]
Éventuellement modifier le redirect du signin réussi pour directement accéder à la page d'accueil
