### ISSUE TITLE
Implémenter la recherche d'événement

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#7]
Si possible sans reload la page.

**Comment by ninojeannet** [comment]
471b02c145bfd4a1d1813c04db6b91fe48f019ac

La recherche est fonctionnel en utilisant des requêtes post
Erreur avec le paginate lorsque l'on effectue un recherche et que l'on affiche la page 2.
Solution potentielle => faire des requêtes GET avec une route spéciale pour la recherche.

**Comment by ninojeannet** [comment]
25b7e6bd6cbbbfe6b4ce5fc18825862acb6f2a1a

Pour éviter l'erreur de la pagination avec un search/search qui se rajoute a chaque fois. Dans mon script javascript, a la place de faire notre requête sur "search/value", je construit l'url avec {{route('search',['']) }} de laravel, puis j'y ajoute ma valeur de recherche.
Il est important d'utiliser route() de laravel pour reconstruire nos urls à chaque fois (pour éviter les search/search,..)
Il reste encore un problème lorsque l'on effectue une recherche, qu'on se déplace sur la page 2, on effectue une nouvelle recherche, l'url est toujours celui de la recherche précédente.
Merci à M. Grunenwald pour son aide.
