### ISSUE TITLE
Création d'événement par les utilisateurs

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#8]

**Comment by daviddasilva1** [comment]
Une vue a été crée. Il faut cliquer dans le nouveau bouton "Créer événement" dans la barre de navigation pour y accéder. Vue vide pour le moment. 96689b604e0c482afcbadeba4649077f30a6bc75

**Comment by Kevin-Laipe** [comment]
Il faudrait revoir le redirect si le form est mal rempli. En l'état, si le validator fails(), on est redirigé directement sur la page de création d'événement.
5460c6c723cc789a162b909f99451936826f8f97

**Comment by Kevin-Laipe** [comment]
> 
> 
> Il faudrait revoir le redirect si le form est mal rempli. En l'état, si le validator fails(), on est redirigé directement sur la page de création d'événement en gardant les champs déjà remplis.
> [5460c6c](https://github.com/HE-Arc/event-ually/commit/5460c6c723cc789a162b909f99451936826f8f97)

On highlight les champs requis, ce qui empêche aussi une redirection foireuse. 3ead672bc6a60662c22bdddbc8b21f0c62cad818

On peut également ajouter des images au événements. 8c50c4f366c22ef03f32f0c7823c604a1de02d6a
