### ISSUE TITLE
Page de profil

### ISSUE THREAD

**Issue by Kevin-Laipe** [HE-Arc/event-ually#9]

**Comment by daviddasilva1** [comment]
Création d'une page vide atteignable seulement si l'user est connecté.
f76fdc16cab2d3939a19a633ced57841bafd8a98

**Comment by daviddasilva1** [comment]
Affichage des événements selon la participation de l'user authentifié. f24c6386b51123f8eb488afa776bb6b54c5c4760

**Comment by daviddasilva1** [comment]
Ajout de css b6d42d46b15e9133091ee7ae24bdcc67d2fddee9

**Comment by Kevin-Laipe** [comment]
Il faut encore corriger les cartes des events sur la page de profil (utiliser les eventBox de la branche search)
